#ifndef __MONSTERMANAGERATTRIBUTECONFTYPE_H_
#define __MONSTERMANAGERATTRIBUTECONFTYPE_H_
enum MonsterManagerAttributeConfigType{
	MonsterManager_MonsterID,
	MonsterManager_Delaytime,
	MonsterManager_Monsternum,
};
#endif