#define WB "wb"
#define SAVEYOURSISTERSQL  "SaveYourSisterSql.sqlite3"
#define SELECT_HERO   "select * from ahero where id = ?"
#define SELECT_SKILL   "select * from bskill where id = ?"
#define SELECT_GEAR    "select * from gear where id = ?"